name: Deploy Tailwind CSS to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Run on Ubuntu (GitHub's server)

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Get the code from the repo

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Setup Node.js environment
      with:
        node-version: 18  # You can adjust the version if needed

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Build the project
      run: npm run build  # Build the Tailwind project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Deploy the build to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Access to your repo
        publish_dir: ./dist  # Publish the 'dist' folder to GitHub Pages